---

antora:
  name: modules
  dir: www
  modules:
    - name: index
      label: "Module 1"
    - name: module-02
      label: "Module 2"
    - name: module-03
      label: "Podman ps"

tabs:
  - name: ">_ lab-user"
    port: 443
    path: /wetty
    type: tty
  - name: Bastion
    url: https://bastion-${guid}.${domain}
  - name: Bastion (external)
    url: https://bastion-${guid}.${domain}
    external: true
