---
- name: Demo Playbook for the ansible-runner API
  hosts: all
  gather_facts: false
  become: false

  tasks:
    - name: Simple debug task
      ansible.builtin.debug:
        msg: "Hello Runner"

    - name: Check if module_01/setup.sh exists
      ansible.builtin.stat:
        path: "./{{ module_dir }}/{{ module_stage }}.sh"
      register: r_script_test

    - name: Execute setup.sh if it exists
      when: r_script_test.stat.exists
      shell: "bash ./{{ module_dir }}/{{ module_stage }}.sh"
      register: r_result

    - name: Output script result
      ansible.builtin.debug:
        var: r_result.stdout
